# SSL certificate bought using the private key, e.g. from Thawte
FatcaCrt: "vendor/robrichards/xmlseclibs/tests/mycert.pem"
# Private key used to get the SSL certificate
FatcaKeyPrivate: "vendor/robrichards/xmlseclibs/tests/privkey.pem"
# public key extracted out of private key above
FatcaKeyPublic: "vendor/shadiakiki1986/FatcaIdesPhp/tests/FatcaIdesPhp/pubkey.pem"

# download folder for IRS public key and schema files
downloadFolder: 'downloads'

# Fatca Sender GIIN
ffaid: 'A1BBCD.00000.XY.123'
# Fatca Receiver GIIN, e.g. IRS
ffaidReceiver: '000000.00000.TA.840'

# make sure www-data is the owner of the below folder
# sudo chown www-data:www-data path/to/folder
# This is in case the references in the unencrypted xml file need to be checked later
ZipBackupFolder: 'bkp'
