# SSL certificate bought using the private key, e.g. from Thawte
FatcaCrt: "etc/ssl/mycert.pem"
# Private key used to get the SSL certificate
FatcaKeyPrivate: "etc/ssl/privkey.pem"
# public key extracted out of private key above
FatcaKeyPublic: "etc/ssl/pubkey.pem"

# Fatca Sender GIIN
ffaid: 'A1BBCD.00000.XY.123'
# Fatca Receiver GIIN, e.g. IRS
ffaidReceiver: '000000.00000.TA.840'

# make sure www-data is the owner of the below folder
# sudo chown www-data:www-data path/to/folder
# This is in case the references in the unencrypted xml file need to be checked later
ZipBackupFolder: 'cache/bkp'

# emailing parameters (optional)
#swiftmailer:
#  host:      some.host.com
#  port: 1234
#  username:  username
#  password:  password

